[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm run build"

[context.production.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
